### ISSUE TITLE
Football Manager Classic support

### ISSUE THREAD

**Issue by s-devaney** [ThanosSiopoudis/FMScoutFramework#40] opened 2015-09-06 21:29 UTC
Given that there is no official editor for FMC (and none planned for FM16), and the only 3rd party editor (FM editor live) has been abandoned by it's developers, there is a large gap which this tool could fill by supporting FMC.

What would be required to get it working with FMC?

**Comment by ThanosSiopoudis** [comment] 2015-09-06 21:31
Hi @s-devaney, as far as I'm aware, the framework does not distinguish between normal or classic mode, therefore any editor made with the framework would potentially support FMC as well.

**Comment by s-devaney** [comment] 2015-09-06 21:41
I believe the offsets are different for FMC, which is why no existing editors (apart from FMEL) support it.

**Comment by joshlatimer** [comment] 2015-09-08 00:24
I don't think the offsets are different at all, I tested my tools a lot with both the classic mode and the normal mode..

Not sure why some tools don't support Classic

**Comment by s-devaney** [comment] 2015-09-08 11:49
That sounds positive. I will take a look tonight to see if I can reproduce.

**Comment by janjongboom** [comment] 2015-09-08 13:14
I know that SI and the guy from FMRTE have been talking at some point (long ago), maybe they paid him some moneys to not make an editor for FM Classic? (pure speculation)

**Comment by ThanosSiopoudis** [comment] 2015-09-08 17:58
Yes, he does have some deal not to make his editor work on Classic mode. I don't know whether there's money involved, or it's just not to piss them off, but it is done on purpose.
From my experience with my MacAssistant RT editor, I can tell you that there's no difference in the addresses.

**Comment by tthordarson** [comment] 2015-09-08 18:06
SI Games have a real time editor for classic mode which costs I think 4.99 GBP to unlock via the in-game store. That's probably why FMRTE are forced to make it not work for classic mode.

**Comment by ThanosSiopoudis** [comment] 2015-09-08 18:09
They have a real time editor for the normal mode, too. The problem is that for Classic mode they have other (paid) unlockables as well, like heal injury, etc.

**Comment by s-devaney** [comment] 2015-09-10 21:04
There's no editor for Classic mode. The real time editor only works for full mode. SI's official reason for no editor is because it would take too much work because of different databases(?)

**Comment by janjongboom** [comment] 2015-09-15 11:24
According to http://www.fmrte.com/forums/topic/3744-fmrte-for-fm-classic-important-please-read/ it's not technical limitation.

**Comment by ThanosSiopoudis** [comment] 2015-09-16 13:38
@s-devaney The database structure is identical. The difference is that the classic db is slimmed down. And a real time editor doesn't edit the database ;)

**Comment by s-devaney** [comment] 2015-09-18 12:56
Just to be clear, is this framework a save game editor, pre-game editor or real time editor?

**Comment by ThanosSiopoudis** [comment] 2015-09-18 13:11
A real-time editor. If you meant that SI doesn't make a classic pre-game editor, that's not entirely true. You can simply move some files around and force the pre-game editor to load a classic db ;)

**Comment by irabbit-topcoder** [comment] 2015-11-04 05:02
Hi @ThanosSiopoudis , I see the Mac assistant is released, is it possible to update this repository to share the load framework for 2016?

**Comment by ThanosSiopoudis** [comment] 2015-11-13 17:21
@irabbit-topcoder MacAssistant RT is a different product and does not use this framework, or work in the same way.
I can only update the framework for the Mac offsets, once I find some time to do so.

**Comment by ThanosSiopoudis** [comment] 2015-11-13 17:22
This is becoming a discussion thread, so I'm closing this ticket, as FMC support is actually working with the framework

**Closed by ThanosSiopoudis** 2015-11-13 17:22 UTC
